sudo: false
language: python
python:
- '2.7'
before_install:
- pip install --upgrade pip
- pip install --upgrade setuptools
- pip install --upgrade pytest
- pip --version
install:
- python setup.py -q install
- python setup.py sdist
- pip install -r requirements/dev.txt
script:
- py.test
after_success:
- coverage xml
- python-codacy-coverage -r coverage.xml
- invoke docs
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/build
  on:
    branch: master
  github_token: "$GH_TOKEN"
env:
  global:
  - secure: B39Cnxz18v0z8LnNhab3Ef7Y+wM1NWUMoWtK0b4hcVTn0LhRjaIdH93Bd8vIzt0lZc9DN9j35Xen+LUSRTV+pnZOIINTWkr+WFM/lU4mcWQtiJb0yHpTnfrQ+rhlkwDnUdYzoMK6TIOLl0bh+894VWhtOZNDp6RjjlZxk0b77GAunVfTNxDO4xO44sg+1zXLOdwUN1VRbqLWvqwVW6bmEBM5GPJCjSQ7398OzVAIWkX3dBNrWrJ+vbckwGwKqqYbXMcDKx5wZx1Nu3I+ahXErADI62Yvy0DQWBftpkRR8HTlHb+GqqNrcPUZ9EMRw778hsNjvYT3wMk7nBDN5tvyo/pDcv33NwtZGn0TgKKhQhBTXdNfLmNAy9r2648Q08aLLDXKl2t4dHmkhi2GoGows/mLqp/vlBmEBa2TJtVL6X6HcGdt+3i6qSUXpBumqQLQuSUcnCi62RwTD9VNGl+buUH/uCoh7bIUO+9m0s0L1hHlvbBghVeNX/eegbIsx6rq/L3iOJ5/PxAK0g1ZfOvxCJrRADNOriewxqFNNXhdRlHnfl/Uk2QoXwojS+frtzN59FHmttilFPZWkAapNdrQnaoe6kbsZz6Yszlb8q7O6aTZDjj75xMeomcXE7H4AOmWzEOBvsrkpUQp7oVg9eWcDO8qUcwMRf6kMn+0eityrUs=
  - secure: JtTQpXOi9Hw/ANQOoLU05OSerAoK5TT/H+SdTmwKagO7T6SYq46ojuZAb+xUP4M7UluLKqYyIOGogmX9BoEPa4ctOdQGHg3r7A9yiUp+lGiUUAIiGcZAfo7uD5gqJ0OpdfD02AhPW8dEqXC6IXVBGJDfKsQtBv0XvT7z6u6uaaR4ja8Ryn0M6A8YF5GrTFNdkuNDGZU/P++kDZ9o05yJvZeXS/7U1cgVxO/WWf2eUKC3/uL78ZDW152VsOXAC2z/o7S6VuqCKROeOmtkXoDEVXdfgqKU+BucWaO+6aLhgqiXKL3fWZN/a2oNhXaq1zKo2GLQxsq4WPZKHrYNtSjjFL/AlbKQ777dmC3EUbvBDb0KtG144/PbqzMMyWFFosauQcQoMg4ZJqGhcQLkcWS049vST/APd/AVczAudh9j92bl7n1vkeJ68cczAKJM733MthDcRHuqbW1mo7gSEl0YV3Kja62wQuufuGGMt2UxJuTdREQXuzB+/6Jqhau78tKMFyXlNbJQIv77E6nt2x1CqoPwVUaLWwC+TTHzUpz7QUO1Bo9TnLjuWW3n2iP20Yze9l7bBusR99Hqw4+UApqSeS39yl07DVEpRk/SNDfCHfAN7VRQurUFUn6xNmXFjwkyNszW8lLzUaYwd1ybD1KnA0azCiHNmGo8P8WGdz1KqGs=
